//export const RECEIVED_SLIDES = 'RECEIVED_SLIDES';
//export const CAPTURE_COMPLETED = 'CAPTURE_COMPLETED';

export const SET_SLIDES = 'SET_SLIDES';

export const FETCH_SLIDES_REQUEST = 'FETCH_SLIDES_REQUEST';
export const FETCH_SLIDES_SUCCESS = 'FETCH_SLIDES_SUCCESS';
export const FETCH_SLIDES_FAILURE = 'FETCH_SLIDES_FAILURE';

export const TAKE_PICTURE_REQUEST = 'TAKE_PICTURE_REQUEST';
export const TAKE_PICTURE_SUCCESS = 'TAKE_PICTURE_SUCCESS';
export const TAKE_PICTURE_FAILURE = 'TAKE_PICTURE_FAILURE';